/**
 * @fileoverview gRPC-Web generated client stub for alis.open.notifications.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v4.24.4
// source: alis/open/notifications/v1/notifications.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var alis_open_validation_v1_validation_pb = require('../../../../alis/open/validation/v1/validation_pb.js')

var google_iam_v1_iam_policy_pb = require('../../../../google/iam/v1/iam_policy_pb.js')
const proto = {};
proto.alis = {};
proto.alis.open = {};
proto.alis.open.notifications = {};
proto.alis.open.notifications.v1 = require('./notifications_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.alis.open.notifications.v1.NotificationsServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.alis.open.notifications.v1.NotificationsServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.open.validation.v1.ValidateMessageRequest,
 *   !proto.alis.open.validation.v1.ValidateMessageResponse>}
 */
const methodDescriptor_NotificationsService_ValidateMessage = new grpc.web.MethodDescriptor(
  '/alis.open.notifications.v1.NotificationsService/ValidateMessage',
  grpc.web.MethodType.UNARY,
  alis_open_validation_v1_validation_pb.ValidateMessageRequest,
  alis_open_validation_v1_validation_pb.ValidateMessageResponse,
  /**
   * @param {!proto.alis.open.validation.v1.ValidateMessageRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  alis_open_validation_v1_validation_pb.ValidateMessageResponse.deserializeBinary
);


/**
 * @param {!proto.alis.open.validation.v1.ValidateMessageRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.alis.open.validation.v1.ValidateMessageResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.alis.open.validation.v1.ValidateMessageResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.open.notifications.v1.NotificationsServiceClient.prototype.validateMessage =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.open.notifications.v1.NotificationsService/ValidateMessage',
      request,
      metadata || {},
      methodDescriptor_NotificationsService_ValidateMessage,
      callback);
};


/**
 * @param {!proto.alis.open.validation.v1.ValidateMessageRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.alis.open.validation.v1.ValidateMessageResponse>}
 *     Promise that resolves to the response
 */
proto.alis.open.notifications.v1.NotificationsServicePromiseClient.prototype.validateMessage =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.open.notifications.v1.NotificationsService/ValidateMessage',
      request,
      metadata || {},
      methodDescriptor_NotificationsService_ValidateMessage);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.open.validation.v1.RetrieveRulesRequest,
 *   !proto.alis.open.validation.v1.RetrieveRulesResponse>}
 */
const methodDescriptor_NotificationsService_RetrieveRules = new grpc.web.MethodDescriptor(
  '/alis.open.notifications.v1.NotificationsService/RetrieveRules',
  grpc.web.MethodType.UNARY,
  alis_open_validation_v1_validation_pb.RetrieveRulesRequest,
  alis_open_validation_v1_validation_pb.RetrieveRulesResponse,
  /**
   * @param {!proto.alis.open.validation.v1.RetrieveRulesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  alis_open_validation_v1_validation_pb.RetrieveRulesResponse.deserializeBinary
);


/**
 * @param {!proto.alis.open.validation.v1.RetrieveRulesRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.alis.open.validation.v1.RetrieveRulesResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.alis.open.validation.v1.RetrieveRulesResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.open.notifications.v1.NotificationsServiceClient.prototype.retrieveRules =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.open.notifications.v1.NotificationsService/RetrieveRules',
      request,
      metadata || {},
      methodDescriptor_NotificationsService_RetrieveRules,
      callback);
};


/**
 * @param {!proto.alis.open.validation.v1.RetrieveRulesRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.alis.open.validation.v1.RetrieveRulesResponse>}
 *     Promise that resolves to the response
 */
proto.alis.open.notifications.v1.NotificationsServicePromiseClient.prototype.retrieveRules =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.open.notifications.v1.NotificationsService/RetrieveRules',
      request,
      metadata || {},
      methodDescriptor_NotificationsService_RetrieveRules);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.iam.v1.TestIamPermissionsRequest,
 *   !proto.google.iam.v1.TestIamPermissionsResponse>}
 */
const methodDescriptor_NotificationsService_TestIamPermissions = new grpc.web.MethodDescriptor(
  '/alis.open.notifications.v1.NotificationsService/TestIamPermissions',
  grpc.web.MethodType.UNARY,
  google_iam_v1_iam_policy_pb.TestIamPermissionsRequest,
  google_iam_v1_iam_policy_pb.TestIamPermissionsResponse,
  /**
   * @param {!proto.google.iam.v1.TestIamPermissionsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_iam_v1_iam_policy_pb.TestIamPermissionsResponse.deserializeBinary
);


/**
 * @param {!proto.google.iam.v1.TestIamPermissionsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.iam.v1.TestIamPermissionsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.iam.v1.TestIamPermissionsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.open.notifications.v1.NotificationsServiceClient.prototype.testIamPermissions =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.open.notifications.v1.NotificationsService/TestIamPermissions',
      request,
      metadata || {},
      methodDescriptor_NotificationsService_TestIamPermissions,
      callback);
};


/**
 * @param {!proto.google.iam.v1.TestIamPermissionsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.iam.v1.TestIamPermissionsResponse>}
 *     Promise that resolves to the response
 */
proto.alis.open.notifications.v1.NotificationsServicePromiseClient.prototype.testIamPermissions =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.open.notifications.v1.NotificationsService/TestIamPermissions',
      request,
      metadata || {},
      methodDescriptor_NotificationsService_TestIamPermissions);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.open.notifications.v1.SendFcmMessageRequest,
 *   !proto.alis.open.notifications.v1.SendFcmMessageResponse>}
 */
const methodDescriptor_NotificationsService_SendFcmMessage = new grpc.web.MethodDescriptor(
  '/alis.open.notifications.v1.NotificationsService/SendFcmMessage',
  grpc.web.MethodType.UNARY,
  proto.alis.open.notifications.v1.SendFcmMessageRequest,
  proto.alis.open.notifications.v1.SendFcmMessageResponse,
  /**
   * @param {!proto.alis.open.notifications.v1.SendFcmMessageRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.alis.open.notifications.v1.SendFcmMessageResponse.deserializeBinary
);


/**
 * @param {!proto.alis.open.notifications.v1.SendFcmMessageRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.alis.open.notifications.v1.SendFcmMessageResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.alis.open.notifications.v1.SendFcmMessageResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.open.notifications.v1.NotificationsServiceClient.prototype.sendFcmMessage =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.open.notifications.v1.NotificationsService/SendFcmMessage',
      request,
      metadata || {},
      methodDescriptor_NotificationsService_SendFcmMessage,
      callback);
};


/**
 * @param {!proto.alis.open.notifications.v1.SendFcmMessageRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.alis.open.notifications.v1.SendFcmMessageResponse>}
 *     Promise that resolves to the response
 */
proto.alis.open.notifications.v1.NotificationsServicePromiseClient.prototype.sendFcmMessage =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.open.notifications.v1.NotificationsService/SendFcmMessage',
      request,
      metadata || {},
      methodDescriptor_NotificationsService_SendFcmMessage);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.open.notifications.v1.BatchSendFcmMessagesRequest,
 *   !proto.alis.open.notifications.v1.BatchSendFcmMessagesResponse>}
 */
const methodDescriptor_NotificationsService_BatchSendFcmMessages = new grpc.web.MethodDescriptor(
  '/alis.open.notifications.v1.NotificationsService/BatchSendFcmMessages',
  grpc.web.MethodType.UNARY,
  proto.alis.open.notifications.v1.BatchSendFcmMessagesRequest,
  proto.alis.open.notifications.v1.BatchSendFcmMessagesResponse,
  /**
   * @param {!proto.alis.open.notifications.v1.BatchSendFcmMessagesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.alis.open.notifications.v1.BatchSendFcmMessagesResponse.deserializeBinary
);


/**
 * @param {!proto.alis.open.notifications.v1.BatchSendFcmMessagesRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.alis.open.notifications.v1.BatchSendFcmMessagesResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.alis.open.notifications.v1.BatchSendFcmMessagesResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.open.notifications.v1.NotificationsServiceClient.prototype.batchSendFcmMessages =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.open.notifications.v1.NotificationsService/BatchSendFcmMessages',
      request,
      metadata || {},
      methodDescriptor_NotificationsService_BatchSendFcmMessages,
      callback);
};


/**
 * @param {!proto.alis.open.notifications.v1.BatchSendFcmMessagesRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.alis.open.notifications.v1.BatchSendFcmMessagesResponse>}
 *     Promise that resolves to the response
 */
proto.alis.open.notifications.v1.NotificationsServicePromiseClient.prototype.batchSendFcmMessages =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.open.notifications.v1.NotificationsService/BatchSendFcmMessages',
      request,
      metadata || {},
      methodDescriptor_NotificationsService_BatchSendFcmMessages);
};


module.exports = proto.alis.open.notifications.v1;

