// source: alis/open/iam/v1/role.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = globalThis;

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.alis.open.iam.v1.Role', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.alis.open.iam.v1.Role = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.alis.open.iam.v1.Role.repeatedFields_, null);
};
goog.inherits(proto.alis.open.iam.v1.Role, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.alis.open.iam.v1.Role.displayName = 'proto.alis.open.iam.v1.Role';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.alis.open.iam.v1.Role.repeatedFields_ = [7,8];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.alis.open.iam.v1.Role.prototype.toObject = function(opt_includeInstance) {
  return proto.alis.open.iam.v1.Role.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.alis.open.iam.v1.Role} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.alis.open.iam.v1.Role.toObject = function(includeInstance, msg) {
  var f, obj = {
name: jspb.Message.getFieldWithDefault(msg, 1, ""),
createTime: (f = msg.getCreateTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
updateTime: (f = msg.getUpdateTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
etag: msg.getEtag_asB64(),
title: jspb.Message.getFieldWithDefault(msg, 5, ""),
description: jspb.Message.getFieldWithDefault(msg, 6, ""),
permissionsList: (f = jspb.Message.getRepeatedField(msg, 7)) == null ? undefined : f,
resourceTypesList: (f = jspb.Message.getRepeatedField(msg, 8)) == null ? undefined : f,
allUsers: jspb.Message.getBooleanFieldWithDefault(msg, 9, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.alis.open.iam.v1.Role}
 */
proto.alis.open.iam.v1.Role.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.alis.open.iam.v1.Role;
  return proto.alis.open.iam.v1.Role.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.alis.open.iam.v1.Role} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.alis.open.iam.v1.Role}
 */
proto.alis.open.iam.v1.Role.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setName(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreateTime(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setUpdateTime(value);
      break;
    case 4:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setEtag(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setTitle(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setDescription(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.addPermissions(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.addResourceTypes(value);
      break;
    case 9:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAllUsers(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.alis.open.iam.v1.Role.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.alis.open.iam.v1.Role.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.alis.open.iam.v1.Role} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.alis.open.iam.v1.Role.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCreateTime();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUpdateTime();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getEtag_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      4,
      f
    );
  }
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getPermissionsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      7,
      f
    );
  }
  f = message.getResourceTypesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      8,
      f
    );
  }
  f = message.getAllUsers();
  if (f) {
    writer.writeBool(
      9,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.alis.open.iam.v1.Role.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.alis.open.iam.v1.Role} returns this
 */
proto.alis.open.iam.v1.Role.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional google.protobuf.Timestamp create_time = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.alis.open.iam.v1.Role.prototype.getCreateTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.alis.open.iam.v1.Role} returns this
*/
proto.alis.open.iam.v1.Role.prototype.setCreateTime = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.alis.open.iam.v1.Role} returns this
 */
proto.alis.open.iam.v1.Role.prototype.clearCreateTime = function() {
  return this.setCreateTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.alis.open.iam.v1.Role.prototype.hasCreateTime = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.Timestamp update_time = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.alis.open.iam.v1.Role.prototype.getUpdateTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.alis.open.iam.v1.Role} returns this
*/
proto.alis.open.iam.v1.Role.prototype.setUpdateTime = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.alis.open.iam.v1.Role} returns this
 */
proto.alis.open.iam.v1.Role.prototype.clearUpdateTime = function() {
  return this.setUpdateTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.alis.open.iam.v1.Role.prototype.hasUpdateTime = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional bytes etag = 4;
 * @return {!(string|Uint8Array)}
 */
proto.alis.open.iam.v1.Role.prototype.getEtag = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * optional bytes etag = 4;
 * This is a type-conversion wrapper around `getEtag()`
 * @return {string}
 */
proto.alis.open.iam.v1.Role.prototype.getEtag_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getEtag()));
};


/**
 * optional bytes etag = 4;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getEtag()`
 * @return {!Uint8Array}
 */
proto.alis.open.iam.v1.Role.prototype.getEtag_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getEtag()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.alis.open.iam.v1.Role} returns this
 */
proto.alis.open.iam.v1.Role.prototype.setEtag = function(value) {
  return jspb.Message.setProto3BytesField(this, 4, value);
};


/**
 * optional string title = 5;
 * @return {string}
 */
proto.alis.open.iam.v1.Role.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.alis.open.iam.v1.Role} returns this
 */
proto.alis.open.iam.v1.Role.prototype.setTitle = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string description = 6;
 * @return {string}
 */
proto.alis.open.iam.v1.Role.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.alis.open.iam.v1.Role} returns this
 */
proto.alis.open.iam.v1.Role.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * repeated string permissions = 7;
 * @return {!Array<string>}
 */
proto.alis.open.iam.v1.Role.prototype.getPermissionsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 7));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.alis.open.iam.v1.Role} returns this
 */
proto.alis.open.iam.v1.Role.prototype.setPermissionsList = function(value) {
  return jspb.Message.setField(this, 7, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.alis.open.iam.v1.Role} returns this
 */
proto.alis.open.iam.v1.Role.prototype.addPermissions = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 7, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.alis.open.iam.v1.Role} returns this
 */
proto.alis.open.iam.v1.Role.prototype.clearPermissionsList = function() {
  return this.setPermissionsList([]);
};


/**
 * repeated string resource_types = 8;
 * @return {!Array<string>}
 */
proto.alis.open.iam.v1.Role.prototype.getResourceTypesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 8));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.alis.open.iam.v1.Role} returns this
 */
proto.alis.open.iam.v1.Role.prototype.setResourceTypesList = function(value) {
  return jspb.Message.setField(this, 8, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.alis.open.iam.v1.Role} returns this
 */
proto.alis.open.iam.v1.Role.prototype.addResourceTypes = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 8, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.alis.open.iam.v1.Role} returns this
 */
proto.alis.open.iam.v1.Role.prototype.clearResourceTypesList = function() {
  return this.setResourceTypesList([]);
};


/**
 * optional bool all_users = 9;
 * @return {boolean}
 */
proto.alis.open.iam.v1.Role.prototype.getAllUsers = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 9, false));
};


/**
 * @param {boolean} value
 * @return {!proto.alis.open.iam.v1.Role} returns this
 */
proto.alis.open.iam.v1.Role.prototype.setAllUsers = function(value) {
  return jspb.Message.setProto3BooleanField(this, 9, value);
};


goog.object.extend(exports, proto.alis.open.iam.v1);

// Below is base64 encoded GeneratedCodeInfo proto
// CicKAgQAEhthbGlzL29wZW4vaWFtL3YxL3JvbGUucHJvdG8YxgggyggKKQoEBAACABIbYWxpcy9vcGVuL2lhbS92MS9yb2xlLnByb3RvGJk9IKA9CikKBAQAAgASG2FsaXMvb3Blbi9pYW0vdjEvcm9sZS5wcm90bxiDPyCKPwopCgQEAAIBEhthbGlzL29wZW4vaWFtL3YxL3JvbGUucHJvdG8Y80AggEEKKQoEBAACARIbYWxpcy9vcGVuL2lhbS92MS9yb2xlLnByb3RvGMRDINFDCikKBAQAAgESG2FsaXMvb3Blbi9pYW0vdjEvcm9sZS5wcm90bxi4RSDHRQopCgQEAAIBEhthbGlzL29wZW4vaWFtL3YxL3JvbGUucHJvdG8Y7UYg+kYKKQoEBAACAhIbYWxpcy9vcGVuL2lhbS92MS9yb2xlLnByb3RvGNNIIOBICikKBAQAAgISG2FsaXMvb3Blbi9pYW0vdjEvcm9sZS5wcm90bxikSyCxSwopCgQEAAICEhthbGlzL29wZW4vaWFtL3YxL3JvbGUucHJvdG8YmE0gp00KKQoEBAACAhIbYWxpcy9vcGVuL2lhbS92MS9yb2xlLnByb3RvGM1OINpOCikKBAQAAgMSG2FsaXMvb3Blbi9pYW0vdjEvcm9sZS5wcm90bxiMUCCTUAopCgQEAAIDEhthbGlzL29wZW4vaWFtL3YxL3JvbGUucHJvdG8YjFcgk1cKKQoEBAACBBIbYWxpcy9vcGVuL2lhbS92MS9yb2xlLnByb3RvGMhYINBYCikKBAQAAgQSG2FsaXMvb3Blbi9pYW0vdjEvcm9sZS5wcm90bxizWiC7WgopCgQEAAIFEhthbGlzL29wZW4vaWFtL3YxL3JvbGUucHJvdG8Y91sghVwKKQoEBAACBRIbYWxpcy9vcGVuL2lhbS92MS9yb2xlLnByb3RvGOhdIPZdCikKBAQAAgYSG2FsaXMvb3Blbi9pYW0vdjEvcm9sZS5wcm90bxi6XyDMXwopCgQEAAIGEhthbGlzL29wZW4vaWFtL3YxL3JvbGUucHJvdG8YuGEgymEKKQoEBAACBhIbYWxpcy9vcGVuL2lhbS92MS9yb2xlLnByb3RvGLZjIMRjCikKBAQAAgYSG2FsaXMvb3Blbi9pYW0vdjEvcm9sZS5wcm90bxjEZSDYZQopCgQEAAIHEhthbGlzL29wZW4vaWFtL3YxL3JvbGUucHJvdG8YhGcgmGcKKQoEBAACBxIbYWxpcy9vcGVuL2lhbS92MS9yb2xlLnByb3RvGIRpIJhpCikKBAQAAgcSG2FsaXMvb3Blbi9pYW0vdjEvcm9sZS5wcm90bxiEayCUawopCgQEAAIHEhthbGlzL29wZW4vaWFtL3YxL3JvbGUucHJvdG8YlG0gqm0KKQoEBAACCBIbYWxpcy9vcGVuL2lhbS92MS9yb2xlLnByb3RvGMpuINVuCikKBAQAAggSG2FsaXMvb3Blbi9pYW0vdjEvcm9sZS5wcm90bxjEcCDPcA==
