/**
 * @fileoverview gRPC-Web generated client stub for alis.open.iam.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v4.24.4
// source: alis/open/iam/v1/user.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var alis_open_iam_v1_iam_pb = require('../../../../alis/open/iam/v1/iam_pb.js')

var alis_open_validation_v1_validation_pb = require('../../../../alis/open/validation/v1/validation_pb.js')

var google_iam_v1_iam_policy_pb = require('../../../../google/iam/v1/iam_policy_pb.js')

var google_iam_v1_policy_pb = require('../../../../google/iam/v1/policy_pb.js')

var google_protobuf_any_pb = require('google-protobuf/google/protobuf/any_pb.js')

var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js')

var google_protobuf_field_mask_pb = require('google-protobuf/google/protobuf/field_mask_pb.js')

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js')
const proto = {};
proto.alis = {};
proto.alis.open = {};
proto.alis.open.iam = {};
proto.alis.open.iam.v1 = require('./user_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.alis.open.iam.v1.UsersServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.alis.open.iam.v1.UsersServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.open.validation.v1.ValidateMessageRequest,
 *   !proto.alis.open.validation.v1.ValidateMessageResponse>}
 */
const methodDescriptor_UsersService_ValidateMessage = new grpc.web.MethodDescriptor(
  '/alis.open.iam.v1.UsersService/ValidateMessage',
  grpc.web.MethodType.UNARY,
  alis_open_validation_v1_validation_pb.ValidateMessageRequest,
  alis_open_validation_v1_validation_pb.ValidateMessageResponse,
  /**
   * @param {!proto.alis.open.validation.v1.ValidateMessageRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  alis_open_validation_v1_validation_pb.ValidateMessageResponse.deserializeBinary
);


/**
 * @param {!proto.alis.open.validation.v1.ValidateMessageRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.alis.open.validation.v1.ValidateMessageResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.alis.open.validation.v1.ValidateMessageResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.open.iam.v1.UsersServiceClient.prototype.validateMessage =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/ValidateMessage',
      request,
      metadata || {},
      methodDescriptor_UsersService_ValidateMessage,
      callback);
};


/**
 * @param {!proto.alis.open.validation.v1.ValidateMessageRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.alis.open.validation.v1.ValidateMessageResponse>}
 *     Promise that resolves to the response
 */
proto.alis.open.iam.v1.UsersServicePromiseClient.prototype.validateMessage =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/ValidateMessage',
      request,
      metadata || {},
      methodDescriptor_UsersService_ValidateMessage);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.open.validation.v1.RetrieveRulesRequest,
 *   !proto.alis.open.validation.v1.RetrieveRulesResponse>}
 */
const methodDescriptor_UsersService_RetrieveRules = new grpc.web.MethodDescriptor(
  '/alis.open.iam.v1.UsersService/RetrieveRules',
  grpc.web.MethodType.UNARY,
  alis_open_validation_v1_validation_pb.RetrieveRulesRequest,
  alis_open_validation_v1_validation_pb.RetrieveRulesResponse,
  /**
   * @param {!proto.alis.open.validation.v1.RetrieveRulesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  alis_open_validation_v1_validation_pb.RetrieveRulesResponse.deserializeBinary
);


/**
 * @param {!proto.alis.open.validation.v1.RetrieveRulesRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.alis.open.validation.v1.RetrieveRulesResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.alis.open.validation.v1.RetrieveRulesResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.open.iam.v1.UsersServiceClient.prototype.retrieveRules =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/RetrieveRules',
      request,
      metadata || {},
      methodDescriptor_UsersService_RetrieveRules,
      callback);
};


/**
 * @param {!proto.alis.open.validation.v1.RetrieveRulesRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.alis.open.validation.v1.RetrieveRulesResponse>}
 *     Promise that resolves to the response
 */
proto.alis.open.iam.v1.UsersServicePromiseClient.prototype.retrieveRules =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/RetrieveRules',
      request,
      metadata || {},
      methodDescriptor_UsersService_RetrieveRules);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.iam.v1.GetIamPolicyRequest,
 *   !proto.google.iam.v1.Policy>}
 */
const methodDescriptor_UsersService_GetIamPolicy = new grpc.web.MethodDescriptor(
  '/alis.open.iam.v1.UsersService/GetIamPolicy',
  grpc.web.MethodType.UNARY,
  google_iam_v1_iam_policy_pb.GetIamPolicyRequest,
  google_iam_v1_policy_pb.Policy,
  /**
   * @param {!proto.google.iam.v1.GetIamPolicyRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_iam_v1_policy_pb.Policy.deserializeBinary
);


/**
 * @param {!proto.google.iam.v1.GetIamPolicyRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.iam.v1.Policy)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.iam.v1.Policy>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.open.iam.v1.UsersServiceClient.prototype.getIamPolicy =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/GetIamPolicy',
      request,
      metadata || {},
      methodDescriptor_UsersService_GetIamPolicy,
      callback);
};


/**
 * @param {!proto.google.iam.v1.GetIamPolicyRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.iam.v1.Policy>}
 *     Promise that resolves to the response
 */
proto.alis.open.iam.v1.UsersServicePromiseClient.prototype.getIamPolicy =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/GetIamPolicy',
      request,
      metadata || {},
      methodDescriptor_UsersService_GetIamPolicy);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.iam.v1.SetIamPolicyRequest,
 *   !proto.google.iam.v1.Policy>}
 */
const methodDescriptor_UsersService_SetIamPolicy = new grpc.web.MethodDescriptor(
  '/alis.open.iam.v1.UsersService/SetIamPolicy',
  grpc.web.MethodType.UNARY,
  google_iam_v1_iam_policy_pb.SetIamPolicyRequest,
  google_iam_v1_policy_pb.Policy,
  /**
   * @param {!proto.google.iam.v1.SetIamPolicyRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_iam_v1_policy_pb.Policy.deserializeBinary
);


/**
 * @param {!proto.google.iam.v1.SetIamPolicyRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.iam.v1.Policy)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.iam.v1.Policy>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.open.iam.v1.UsersServiceClient.prototype.setIamPolicy =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/SetIamPolicy',
      request,
      metadata || {},
      methodDescriptor_UsersService_SetIamPolicy,
      callback);
};


/**
 * @param {!proto.google.iam.v1.SetIamPolicyRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.iam.v1.Policy>}
 *     Promise that resolves to the response
 */
proto.alis.open.iam.v1.UsersServicePromiseClient.prototype.setIamPolicy =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/SetIamPolicy',
      request,
      metadata || {},
      methodDescriptor_UsersService_SetIamPolicy);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.iam.v1.TestIamPermissionsRequest,
 *   !proto.google.iam.v1.TestIamPermissionsResponse>}
 */
const methodDescriptor_UsersService_TestIamPermissions = new grpc.web.MethodDescriptor(
  '/alis.open.iam.v1.UsersService/TestIamPermissions',
  grpc.web.MethodType.UNARY,
  google_iam_v1_iam_policy_pb.TestIamPermissionsRequest,
  google_iam_v1_iam_policy_pb.TestIamPermissionsResponse,
  /**
   * @param {!proto.google.iam.v1.TestIamPermissionsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_iam_v1_iam_policy_pb.TestIamPermissionsResponse.deserializeBinary
);


/**
 * @param {!proto.google.iam.v1.TestIamPermissionsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.iam.v1.TestIamPermissionsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.iam.v1.TestIamPermissionsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.open.iam.v1.UsersServiceClient.prototype.testIamPermissions =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/TestIamPermissions',
      request,
      metadata || {},
      methodDescriptor_UsersService_TestIamPermissions,
      callback);
};


/**
 * @param {!proto.google.iam.v1.TestIamPermissionsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.iam.v1.TestIamPermissionsResponse>}
 *     Promise that resolves to the response
 */
proto.alis.open.iam.v1.UsersServicePromiseClient.prototype.testIamPermissions =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/TestIamPermissions',
      request,
      metadata || {},
      methodDescriptor_UsersService_TestIamPermissions);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.open.iam.v1.AddIamBindingsRequest,
 *   !proto.google.iam.v1.Policy>}
 */
const methodDescriptor_UsersService_AddIamBindings = new grpc.web.MethodDescriptor(
  '/alis.open.iam.v1.UsersService/AddIamBindings',
  grpc.web.MethodType.UNARY,
  alis_open_iam_v1_iam_pb.AddIamBindingsRequest,
  google_iam_v1_policy_pb.Policy,
  /**
   * @param {!proto.alis.open.iam.v1.AddIamBindingsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_iam_v1_policy_pb.Policy.deserializeBinary
);


/**
 * @param {!proto.alis.open.iam.v1.AddIamBindingsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.iam.v1.Policy)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.iam.v1.Policy>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.open.iam.v1.UsersServiceClient.prototype.addIamBindings =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/AddIamBindings',
      request,
      metadata || {},
      methodDescriptor_UsersService_AddIamBindings,
      callback);
};


/**
 * @param {!proto.alis.open.iam.v1.AddIamBindingsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.iam.v1.Policy>}
 *     Promise that resolves to the response
 */
proto.alis.open.iam.v1.UsersServicePromiseClient.prototype.addIamBindings =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/AddIamBindings',
      request,
      metadata || {},
      methodDescriptor_UsersService_AddIamBindings);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.open.iam.v1.RemoveIamBindingsRequest,
 *   !proto.google.iam.v1.Policy>}
 */
const methodDescriptor_UsersService_RemoveIamBindings = new grpc.web.MethodDescriptor(
  '/alis.open.iam.v1.UsersService/RemoveIamBindings',
  grpc.web.MethodType.UNARY,
  alis_open_iam_v1_iam_pb.RemoveIamBindingsRequest,
  google_iam_v1_policy_pb.Policy,
  /**
   * @param {!proto.alis.open.iam.v1.RemoveIamBindingsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_iam_v1_policy_pb.Policy.deserializeBinary
);


/**
 * @param {!proto.alis.open.iam.v1.RemoveIamBindingsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.iam.v1.Policy)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.iam.v1.Policy>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.open.iam.v1.UsersServiceClient.prototype.removeIamBindings =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/RemoveIamBindings',
      request,
      metadata || {},
      methodDescriptor_UsersService_RemoveIamBindings,
      callback);
};


/**
 * @param {!proto.alis.open.iam.v1.RemoveIamBindingsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.iam.v1.Policy>}
 *     Promise that resolves to the response
 */
proto.alis.open.iam.v1.UsersServicePromiseClient.prototype.removeIamBindings =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/RemoveIamBindings',
      request,
      metadata || {},
      methodDescriptor_UsersService_RemoveIamBindings);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.open.iam.v1.GetUserRequest,
 *   !proto.alis.open.iam.v1.User>}
 */
const methodDescriptor_UsersService_GetUser = new grpc.web.MethodDescriptor(
  '/alis.open.iam.v1.UsersService/GetUser',
  grpc.web.MethodType.UNARY,
  proto.alis.open.iam.v1.GetUserRequest,
  proto.alis.open.iam.v1.User,
  /**
   * @param {!proto.alis.open.iam.v1.GetUserRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.alis.open.iam.v1.User.deserializeBinary
);


/**
 * @param {!proto.alis.open.iam.v1.GetUserRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.alis.open.iam.v1.User)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.alis.open.iam.v1.User>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.open.iam.v1.UsersServiceClient.prototype.getUser =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/GetUser',
      request,
      metadata || {},
      methodDescriptor_UsersService_GetUser,
      callback);
};


/**
 * @param {!proto.alis.open.iam.v1.GetUserRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.alis.open.iam.v1.User>}
 *     Promise that resolves to the response
 */
proto.alis.open.iam.v1.UsersServicePromiseClient.prototype.getUser =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/GetUser',
      request,
      metadata || {},
      methodDescriptor_UsersService_GetUser);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.open.iam.v1.CreateUserRequest,
 *   !proto.alis.open.iam.v1.User>}
 */
const methodDescriptor_UsersService_CreateUser = new grpc.web.MethodDescriptor(
  '/alis.open.iam.v1.UsersService/CreateUser',
  grpc.web.MethodType.UNARY,
  proto.alis.open.iam.v1.CreateUserRequest,
  proto.alis.open.iam.v1.User,
  /**
   * @param {!proto.alis.open.iam.v1.CreateUserRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.alis.open.iam.v1.User.deserializeBinary
);


/**
 * @param {!proto.alis.open.iam.v1.CreateUserRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.alis.open.iam.v1.User)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.alis.open.iam.v1.User>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.open.iam.v1.UsersServiceClient.prototype.createUser =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/CreateUser',
      request,
      metadata || {},
      methodDescriptor_UsersService_CreateUser,
      callback);
};


/**
 * @param {!proto.alis.open.iam.v1.CreateUserRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.alis.open.iam.v1.User>}
 *     Promise that resolves to the response
 */
proto.alis.open.iam.v1.UsersServicePromiseClient.prototype.createUser =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/CreateUser',
      request,
      metadata || {},
      methodDescriptor_UsersService_CreateUser);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.open.iam.v1.UpdateUserRequest,
 *   !proto.alis.open.iam.v1.User>}
 */
const methodDescriptor_UsersService_UpdateUser = new grpc.web.MethodDescriptor(
  '/alis.open.iam.v1.UsersService/UpdateUser',
  grpc.web.MethodType.UNARY,
  proto.alis.open.iam.v1.UpdateUserRequest,
  proto.alis.open.iam.v1.User,
  /**
   * @param {!proto.alis.open.iam.v1.UpdateUserRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.alis.open.iam.v1.User.deserializeBinary
);


/**
 * @param {!proto.alis.open.iam.v1.UpdateUserRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.alis.open.iam.v1.User)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.alis.open.iam.v1.User>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.open.iam.v1.UsersServiceClient.prototype.updateUser =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/UpdateUser',
      request,
      metadata || {},
      methodDescriptor_UsersService_UpdateUser,
      callback);
};


/**
 * @param {!proto.alis.open.iam.v1.UpdateUserRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.alis.open.iam.v1.User>}
 *     Promise that resolves to the response
 */
proto.alis.open.iam.v1.UsersServicePromiseClient.prototype.updateUser =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/UpdateUser',
      request,
      metadata || {},
      methodDescriptor_UsersService_UpdateUser);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.open.iam.v1.DeleteUserRequest,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_UsersService_DeleteUser = new grpc.web.MethodDescriptor(
  '/alis.open.iam.v1.UsersService/DeleteUser',
  grpc.web.MethodType.UNARY,
  proto.alis.open.iam.v1.DeleteUserRequest,
  google_protobuf_empty_pb.Empty,
  /**
   * @param {!proto.alis.open.iam.v1.DeleteUserRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_protobuf_empty_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.alis.open.iam.v1.DeleteUserRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.open.iam.v1.UsersServiceClient.prototype.deleteUser =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/DeleteUser',
      request,
      metadata || {},
      methodDescriptor_UsersService_DeleteUser,
      callback);
};


/**
 * @param {!proto.alis.open.iam.v1.DeleteUserRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.alis.open.iam.v1.UsersServicePromiseClient.prototype.deleteUser =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/DeleteUser',
      request,
      metadata || {},
      methodDescriptor_UsersService_DeleteUser);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.open.iam.v1.ListUsersRequest,
 *   !proto.alis.open.iam.v1.ListUsersResponse>}
 */
const methodDescriptor_UsersService_ListUsers = new grpc.web.MethodDescriptor(
  '/alis.open.iam.v1.UsersService/ListUsers',
  grpc.web.MethodType.UNARY,
  proto.alis.open.iam.v1.ListUsersRequest,
  proto.alis.open.iam.v1.ListUsersResponse,
  /**
   * @param {!proto.alis.open.iam.v1.ListUsersRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.alis.open.iam.v1.ListUsersResponse.deserializeBinary
);


/**
 * @param {!proto.alis.open.iam.v1.ListUsersRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.alis.open.iam.v1.ListUsersResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.alis.open.iam.v1.ListUsersResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.open.iam.v1.UsersServiceClient.prototype.listUsers =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/ListUsers',
      request,
      metadata || {},
      methodDescriptor_UsersService_ListUsers,
      callback);
};


/**
 * @param {!proto.alis.open.iam.v1.ListUsersRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.alis.open.iam.v1.ListUsersResponse>}
 *     Promise that resolves to the response
 */
proto.alis.open.iam.v1.UsersServicePromiseClient.prototype.listUsers =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/ListUsers',
      request,
      metadata || {},
      methodDescriptor_UsersService_ListUsers);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.open.iam.v1.RetrieveUserByEmailRequest,
 *   !proto.alis.open.iam.v1.User>}
 */
const methodDescriptor_UsersService_RetrieveUserByEmail = new grpc.web.MethodDescriptor(
  '/alis.open.iam.v1.UsersService/RetrieveUserByEmail',
  grpc.web.MethodType.UNARY,
  proto.alis.open.iam.v1.RetrieveUserByEmailRequest,
  proto.alis.open.iam.v1.User,
  /**
   * @param {!proto.alis.open.iam.v1.RetrieveUserByEmailRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.alis.open.iam.v1.User.deserializeBinary
);


/**
 * @param {!proto.alis.open.iam.v1.RetrieveUserByEmailRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.alis.open.iam.v1.User)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.alis.open.iam.v1.User>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.open.iam.v1.UsersServiceClient.prototype.retrieveUserByEmail =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/RetrieveUserByEmail',
      request,
      metadata || {},
      methodDescriptor_UsersService_RetrieveUserByEmail,
      callback);
};


/**
 * @param {!proto.alis.open.iam.v1.RetrieveUserByEmailRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.alis.open.iam.v1.User>}
 *     Promise that resolves to the response
 */
proto.alis.open.iam.v1.UsersServicePromiseClient.prototype.retrieveUserByEmail =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/RetrieveUserByEmail',
      request,
      metadata || {},
      methodDescriptor_UsersService_RetrieveUserByEmail);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.open.iam.v1.LookupUserRequest,
 *   !proto.alis.open.iam.v1.LookupUserResponse>}
 */
const methodDescriptor_UsersService_LookupUser = new grpc.web.MethodDescriptor(
  '/alis.open.iam.v1.UsersService/LookupUser',
  grpc.web.MethodType.UNARY,
  proto.alis.open.iam.v1.LookupUserRequest,
  proto.alis.open.iam.v1.LookupUserResponse,
  /**
   * @param {!proto.alis.open.iam.v1.LookupUserRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.alis.open.iam.v1.LookupUserResponse.deserializeBinary
);


/**
 * @param {!proto.alis.open.iam.v1.LookupUserRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.alis.open.iam.v1.LookupUserResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.alis.open.iam.v1.LookupUserResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.open.iam.v1.UsersServiceClient.prototype.lookupUser =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/LookupUser',
      request,
      metadata || {},
      methodDescriptor_UsersService_LookupUser,
      callback);
};


/**
 * @param {!proto.alis.open.iam.v1.LookupUserRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.alis.open.iam.v1.LookupUserResponse>}
 *     Promise that resolves to the response
 */
proto.alis.open.iam.v1.UsersServicePromiseClient.prototype.lookupUser =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/LookupUser',
      request,
      metadata || {},
      methodDescriptor_UsersService_LookupUser);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.open.iam.v1.BatchRetrieveMaskedUsersRequest,
 *   !proto.alis.open.iam.v1.BatchRetrieveMaskedUsersResponse>}
 */
const methodDescriptor_UsersService_BatchRetrieveMaskedUsers = new grpc.web.MethodDescriptor(
  '/alis.open.iam.v1.UsersService/BatchRetrieveMaskedUsers',
  grpc.web.MethodType.UNARY,
  proto.alis.open.iam.v1.BatchRetrieveMaskedUsersRequest,
  proto.alis.open.iam.v1.BatchRetrieveMaskedUsersResponse,
  /**
   * @param {!proto.alis.open.iam.v1.BatchRetrieveMaskedUsersRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.alis.open.iam.v1.BatchRetrieveMaskedUsersResponse.deserializeBinary
);


/**
 * @param {!proto.alis.open.iam.v1.BatchRetrieveMaskedUsersRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.alis.open.iam.v1.BatchRetrieveMaskedUsersResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.alis.open.iam.v1.BatchRetrieveMaskedUsersResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.open.iam.v1.UsersServiceClient.prototype.batchRetrieveMaskedUsers =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/BatchRetrieveMaskedUsers',
      request,
      metadata || {},
      methodDescriptor_UsersService_BatchRetrieveMaskedUsers,
      callback);
};


/**
 * @param {!proto.alis.open.iam.v1.BatchRetrieveMaskedUsersRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.alis.open.iam.v1.BatchRetrieveMaskedUsersResponse>}
 *     Promise that resolves to the response
 */
proto.alis.open.iam.v1.UsersServicePromiseClient.prototype.batchRetrieveMaskedUsers =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/BatchRetrieveMaskedUsers',
      request,
      metadata || {},
      methodDescriptor_UsersService_BatchRetrieveMaskedUsers);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.open.iam.v1.RetrieveMaskedUsersRequest,
 *   !proto.alis.open.iam.v1.RetrieveMaskedUsersResponse>}
 */
const methodDescriptor_UsersService_RetrieveMaskedUsers = new grpc.web.MethodDescriptor(
  '/alis.open.iam.v1.UsersService/RetrieveMaskedUsers',
  grpc.web.MethodType.UNARY,
  proto.alis.open.iam.v1.RetrieveMaskedUsersRequest,
  proto.alis.open.iam.v1.RetrieveMaskedUsersResponse,
  /**
   * @param {!proto.alis.open.iam.v1.RetrieveMaskedUsersRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.alis.open.iam.v1.RetrieveMaskedUsersResponse.deserializeBinary
);


/**
 * @param {!proto.alis.open.iam.v1.RetrieveMaskedUsersRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.alis.open.iam.v1.RetrieveMaskedUsersResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.alis.open.iam.v1.RetrieveMaskedUsersResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.open.iam.v1.UsersServiceClient.prototype.retrieveMaskedUsers =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/RetrieveMaskedUsers',
      request,
      metadata || {},
      methodDescriptor_UsersService_RetrieveMaskedUsers,
      callback);
};


/**
 * @param {!proto.alis.open.iam.v1.RetrieveMaskedUsersRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.alis.open.iam.v1.RetrieveMaskedUsersResponse>}
 *     Promise that resolves to the response
 */
proto.alis.open.iam.v1.UsersServicePromiseClient.prototype.retrieveMaskedUsers =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/RetrieveMaskedUsers',
      request,
      metadata || {},
      methodDescriptor_UsersService_RetrieveMaskedUsers);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.open.iam.v1.RetrieveMaskedUserRequest,
 *   !proto.alis.open.iam.v1.MaskedUser>}
 */
const methodDescriptor_UsersService_RetrieveMaskedUser = new grpc.web.MethodDescriptor(
  '/alis.open.iam.v1.UsersService/RetrieveMaskedUser',
  grpc.web.MethodType.UNARY,
  proto.alis.open.iam.v1.RetrieveMaskedUserRequest,
  proto.alis.open.iam.v1.MaskedUser,
  /**
   * @param {!proto.alis.open.iam.v1.RetrieveMaskedUserRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.alis.open.iam.v1.MaskedUser.deserializeBinary
);


/**
 * @param {!proto.alis.open.iam.v1.RetrieveMaskedUserRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.alis.open.iam.v1.MaskedUser)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.alis.open.iam.v1.MaskedUser>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.open.iam.v1.UsersServiceClient.prototype.retrieveMaskedUser =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/RetrieveMaskedUser',
      request,
      metadata || {},
      methodDescriptor_UsersService_RetrieveMaskedUser,
      callback);
};


/**
 * @param {!proto.alis.open.iam.v1.RetrieveMaskedUserRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.alis.open.iam.v1.MaskedUser>}
 *     Promise that resolves to the response
 */
proto.alis.open.iam.v1.UsersServicePromiseClient.prototype.retrieveMaskedUser =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/RetrieveMaskedUser',
      request,
      metadata || {},
      methodDescriptor_UsersService_RetrieveMaskedUser);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.open.iam.v1.EditUserInfoRequest,
 *   !proto.alis.open.iam.v1.User>}
 */
const methodDescriptor_UsersService_EditUserInfo = new grpc.web.MethodDescriptor(
  '/alis.open.iam.v1.UsersService/EditUserInfo',
  grpc.web.MethodType.UNARY,
  proto.alis.open.iam.v1.EditUserInfoRequest,
  proto.alis.open.iam.v1.User,
  /**
   * @param {!proto.alis.open.iam.v1.EditUserInfoRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.alis.open.iam.v1.User.deserializeBinary
);


/**
 * @param {!proto.alis.open.iam.v1.EditUserInfoRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.alis.open.iam.v1.User)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.alis.open.iam.v1.User>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.open.iam.v1.UsersServiceClient.prototype.editUserInfo =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/EditUserInfo',
      request,
      metadata || {},
      methodDescriptor_UsersService_EditUserInfo,
      callback);
};


/**
 * @param {!proto.alis.open.iam.v1.EditUserInfoRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.alis.open.iam.v1.User>}
 *     Promise that resolves to the response
 */
proto.alis.open.iam.v1.UsersServicePromiseClient.prototype.editUserInfo =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/EditUserInfo',
      request,
      metadata || {},
      methodDescriptor_UsersService_EditUserInfo);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.open.iam.v1.EditUserMetadataRequest,
 *   !proto.alis.open.iam.v1.User>}
 */
const methodDescriptor_UsersService_EditUserMetadata = new grpc.web.MethodDescriptor(
  '/alis.open.iam.v1.UsersService/EditUserMetadata',
  grpc.web.MethodType.UNARY,
  proto.alis.open.iam.v1.EditUserMetadataRequest,
  proto.alis.open.iam.v1.User,
  /**
   * @param {!proto.alis.open.iam.v1.EditUserMetadataRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.alis.open.iam.v1.User.deserializeBinary
);


/**
 * @param {!proto.alis.open.iam.v1.EditUserMetadataRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.alis.open.iam.v1.User)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.alis.open.iam.v1.User>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.open.iam.v1.UsersServiceClient.prototype.editUserMetadata =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/EditUserMetadata',
      request,
      metadata || {},
      methodDescriptor_UsersService_EditUserMetadata,
      callback);
};


/**
 * @param {!proto.alis.open.iam.v1.EditUserMetadataRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.alis.open.iam.v1.User>}
 *     Promise that resolves to the response
 */
proto.alis.open.iam.v1.UsersServicePromiseClient.prototype.editUserMetadata =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/EditUserMetadata',
      request,
      metadata || {},
      methodDescriptor_UsersService_EditUserMetadata);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.open.iam.v1.RetrieveMyUserRequest,
 *   !proto.alis.open.iam.v1.User>}
 */
const methodDescriptor_UsersService_RetrieveMyUser = new grpc.web.MethodDescriptor(
  '/alis.open.iam.v1.UsersService/RetrieveMyUser',
  grpc.web.MethodType.UNARY,
  proto.alis.open.iam.v1.RetrieveMyUserRequest,
  proto.alis.open.iam.v1.User,
  /**
   * @param {!proto.alis.open.iam.v1.RetrieveMyUserRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.alis.open.iam.v1.User.deserializeBinary
);


/**
 * @param {!proto.alis.open.iam.v1.RetrieveMyUserRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.alis.open.iam.v1.User)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.alis.open.iam.v1.User>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.open.iam.v1.UsersServiceClient.prototype.retrieveMyUser =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/RetrieveMyUser',
      request,
      metadata || {},
      methodDescriptor_UsersService_RetrieveMyUser,
      callback);
};


/**
 * @param {!proto.alis.open.iam.v1.RetrieveMyUserRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.alis.open.iam.v1.User>}
 *     Promise that resolves to the response
 */
proto.alis.open.iam.v1.UsersServicePromiseClient.prototype.retrieveMyUser =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/RetrieveMyUser',
      request,
      metadata || {},
      methodDescriptor_UsersService_RetrieveMyUser);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.open.iam.v1.EditMyInfoRequest,
 *   !proto.alis.open.iam.v1.User>}
 */
const methodDescriptor_UsersService_EditMyInfo = new grpc.web.MethodDescriptor(
  '/alis.open.iam.v1.UsersService/EditMyInfo',
  grpc.web.MethodType.UNARY,
  proto.alis.open.iam.v1.EditMyInfoRequest,
  proto.alis.open.iam.v1.User,
  /**
   * @param {!proto.alis.open.iam.v1.EditMyInfoRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.alis.open.iam.v1.User.deserializeBinary
);


/**
 * @param {!proto.alis.open.iam.v1.EditMyInfoRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.alis.open.iam.v1.User)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.alis.open.iam.v1.User>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.open.iam.v1.UsersServiceClient.prototype.editMyInfo =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/EditMyInfo',
      request,
      metadata || {},
      methodDescriptor_UsersService_EditMyInfo,
      callback);
};


/**
 * @param {!proto.alis.open.iam.v1.EditMyInfoRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.alis.open.iam.v1.User>}
 *     Promise that resolves to the response
 */
proto.alis.open.iam.v1.UsersServicePromiseClient.prototype.editMyInfo =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/EditMyInfo',
      request,
      metadata || {},
      methodDescriptor_UsersService_EditMyInfo);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.open.iam.v1.EditMyMetadataRequest,
 *   !proto.alis.open.iam.v1.User>}
 */
const methodDescriptor_UsersService_EditMyMetadata = new grpc.web.MethodDescriptor(
  '/alis.open.iam.v1.UsersService/EditMyMetadata',
  grpc.web.MethodType.UNARY,
  proto.alis.open.iam.v1.EditMyMetadataRequest,
  proto.alis.open.iam.v1.User,
  /**
   * @param {!proto.alis.open.iam.v1.EditMyMetadataRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.alis.open.iam.v1.User.deserializeBinary
);


/**
 * @param {!proto.alis.open.iam.v1.EditMyMetadataRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.alis.open.iam.v1.User)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.alis.open.iam.v1.User>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.open.iam.v1.UsersServiceClient.prototype.editMyMetadata =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/EditMyMetadata',
      request,
      metadata || {},
      methodDescriptor_UsersService_EditMyMetadata,
      callback);
};


/**
 * @param {!proto.alis.open.iam.v1.EditMyMetadataRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.alis.open.iam.v1.User>}
 *     Promise that resolves to the response
 */
proto.alis.open.iam.v1.UsersServicePromiseClient.prototype.editMyMetadata =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/EditMyMetadata',
      request,
      metadata || {},
      methodDescriptor_UsersService_EditMyMetadata);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.open.iam.v1.RemoveMyUserRequest,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_UsersService_RemoveMyUser = new grpc.web.MethodDescriptor(
  '/alis.open.iam.v1.UsersService/RemoveMyUser',
  grpc.web.MethodType.UNARY,
  proto.alis.open.iam.v1.RemoveMyUserRequest,
  google_protobuf_empty_pb.Empty,
  /**
   * @param {!proto.alis.open.iam.v1.RemoveMyUserRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_protobuf_empty_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.alis.open.iam.v1.RemoveMyUserRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.open.iam.v1.UsersServiceClient.prototype.removeMyUser =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/RemoveMyUser',
      request,
      metadata || {},
      methodDescriptor_UsersService_RemoveMyUser,
      callback);
};


/**
 * @param {!proto.alis.open.iam.v1.RemoveMyUserRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.alis.open.iam.v1.UsersServicePromiseClient.prototype.removeMyUser =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/RemoveMyUser',
      request,
      metadata || {},
      methodDescriptor_UsersService_RemoveMyUser);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.open.iam.v1.SyncToGoogleGroupRequest,
 *   !proto.alis.open.iam.v1.SyncToGoogleGroupResponse>}
 */
const methodDescriptor_UsersService_SyncToGoogleGroup = new grpc.web.MethodDescriptor(
  '/alis.open.iam.v1.UsersService/SyncToGoogleGroup',
  grpc.web.MethodType.UNARY,
  proto.alis.open.iam.v1.SyncToGoogleGroupRequest,
  proto.alis.open.iam.v1.SyncToGoogleGroupResponse,
  /**
   * @param {!proto.alis.open.iam.v1.SyncToGoogleGroupRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.alis.open.iam.v1.SyncToGoogleGroupResponse.deserializeBinary
);


/**
 * @param {!proto.alis.open.iam.v1.SyncToGoogleGroupRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.alis.open.iam.v1.SyncToGoogleGroupResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.alis.open.iam.v1.SyncToGoogleGroupResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.open.iam.v1.UsersServiceClient.prototype.syncToGoogleGroup =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/SyncToGoogleGroup',
      request,
      metadata || {},
      methodDescriptor_UsersService_SyncToGoogleGroup,
      callback);
};


/**
 * @param {!proto.alis.open.iam.v1.SyncToGoogleGroupRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.alis.open.iam.v1.SyncToGoogleGroupResponse>}
 *     Promise that resolves to the response
 */
proto.alis.open.iam.v1.UsersServicePromiseClient.prototype.syncToGoogleGroup =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/SyncToGoogleGroup',
      request,
      metadata || {},
      methodDescriptor_UsersService_SyncToGoogleGroup);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.open.iam.v1.SetUserPictureRequest,
 *   !proto.alis.open.iam.v1.SetUserPictureResponse>}
 */
const methodDescriptor_UsersService_SetUserPicture = new grpc.web.MethodDescriptor(
  '/alis.open.iam.v1.UsersService/SetUserPicture',
  grpc.web.MethodType.UNARY,
  proto.alis.open.iam.v1.SetUserPictureRequest,
  proto.alis.open.iam.v1.SetUserPictureResponse,
  /**
   * @param {!proto.alis.open.iam.v1.SetUserPictureRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.alis.open.iam.v1.SetUserPictureResponse.deserializeBinary
);


/**
 * @param {!proto.alis.open.iam.v1.SetUserPictureRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.alis.open.iam.v1.SetUserPictureResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.alis.open.iam.v1.SetUserPictureResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.open.iam.v1.UsersServiceClient.prototype.setUserPicture =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/SetUserPicture',
      request,
      metadata || {},
      methodDescriptor_UsersService_SetUserPicture,
      callback);
};


/**
 * @param {!proto.alis.open.iam.v1.SetUserPictureRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.alis.open.iam.v1.SetUserPictureResponse>}
 *     Promise that resolves to the response
 */
proto.alis.open.iam.v1.UsersServicePromiseClient.prototype.setUserPicture =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.open.iam.v1.UsersService/SetUserPicture',
      request,
      metadata || {},
      methodDescriptor_UsersService_SetUserPicture);
};


module.exports = proto.alis.open.iam.v1;

