/**
 * @fileoverview gRPC-Web generated client stub for alis.open.agent.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v4.24.4
// source: alis/open/agent/v1/agent.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_api_annotations_pb = require('../../../../google/api/annotations_pb.js')

var google_api_client_pb = require('../../../../google/api/client_pb.js')

var google_api_field_behavior_pb = require('../../../../google/api/field_behavior_pb.js')

var google_protobuf_any_pb = require('google-protobuf/google/protobuf/any_pb.js')

var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js')

var google_protobuf_struct_pb = require('google-protobuf/google/protobuf/struct_pb.js')

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js')
const proto = {};
proto.alis = {};
proto.alis.open = {};
proto.alis.open.agent = {};
proto.alis.open.agent.v1 = require('./agent_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.alis.open.agent.v1.A2AServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.alis.open.agent.v1.A2AServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.open.agent.v1.SendMessageRequest,
 *   !proto.alis.open.agent.v1.SendMessageResponse>}
 */
const methodDescriptor_A2AService_SendMessage = new grpc.web.MethodDescriptor(
  '/alis.open.agent.v1.A2AService/SendMessage',
  grpc.web.MethodType.UNARY,
  proto.alis.open.agent.v1.SendMessageRequest,
  proto.alis.open.agent.v1.SendMessageResponse,
  /**
   * @param {!proto.alis.open.agent.v1.SendMessageRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.alis.open.agent.v1.SendMessageResponse.deserializeBinary
);


/**
 * @param {!proto.alis.open.agent.v1.SendMessageRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.alis.open.agent.v1.SendMessageResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.alis.open.agent.v1.SendMessageResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.open.agent.v1.A2AServiceClient.prototype.sendMessage =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.open.agent.v1.A2AService/SendMessage',
      request,
      metadata || {},
      methodDescriptor_A2AService_SendMessage,
      callback);
};


/**
 * @param {!proto.alis.open.agent.v1.SendMessageRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.alis.open.agent.v1.SendMessageResponse>}
 *     Promise that resolves to the response
 */
proto.alis.open.agent.v1.A2AServicePromiseClient.prototype.sendMessage =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.open.agent.v1.A2AService/SendMessage',
      request,
      metadata || {},
      methodDescriptor_A2AService_SendMessage);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.open.agent.v1.SendMessageRequest,
 *   !proto.alis.open.agent.v1.StreamResponse>}
 */
const methodDescriptor_A2AService_SendStreamingMessage = new grpc.web.MethodDescriptor(
  '/alis.open.agent.v1.A2AService/SendStreamingMessage',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.alis.open.agent.v1.SendMessageRequest,
  proto.alis.open.agent.v1.StreamResponse,
  /**
   * @param {!proto.alis.open.agent.v1.SendMessageRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.alis.open.agent.v1.StreamResponse.deserializeBinary
);


/**
 * @param {!proto.alis.open.agent.v1.SendMessageRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.alis.open.agent.v1.StreamResponse>}
 *     The XHR Node Readable Stream
 */
proto.alis.open.agent.v1.A2AServiceClient.prototype.sendStreamingMessage =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/alis.open.agent.v1.A2AService/SendStreamingMessage',
      request,
      metadata || {},
      methodDescriptor_A2AService_SendStreamingMessage);
};


/**
 * @param {!proto.alis.open.agent.v1.SendMessageRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.alis.open.agent.v1.StreamResponse>}
 *     The XHR Node Readable Stream
 */
proto.alis.open.agent.v1.A2AServicePromiseClient.prototype.sendStreamingMessage =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/alis.open.agent.v1.A2AService/SendStreamingMessage',
      request,
      metadata || {},
      methodDescriptor_A2AService_SendStreamingMessage);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.open.agent.v1.GetTaskRequest,
 *   !proto.alis.open.agent.v1.Task>}
 */
const methodDescriptor_A2AService_GetTask = new grpc.web.MethodDescriptor(
  '/alis.open.agent.v1.A2AService/GetTask',
  grpc.web.MethodType.UNARY,
  proto.alis.open.agent.v1.GetTaskRequest,
  proto.alis.open.agent.v1.Task,
  /**
   * @param {!proto.alis.open.agent.v1.GetTaskRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.alis.open.agent.v1.Task.deserializeBinary
);


/**
 * @param {!proto.alis.open.agent.v1.GetTaskRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.alis.open.agent.v1.Task)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.alis.open.agent.v1.Task>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.open.agent.v1.A2AServiceClient.prototype.getTask =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.open.agent.v1.A2AService/GetTask',
      request,
      metadata || {},
      methodDescriptor_A2AService_GetTask,
      callback);
};


/**
 * @param {!proto.alis.open.agent.v1.GetTaskRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.alis.open.agent.v1.Task>}
 *     Promise that resolves to the response
 */
proto.alis.open.agent.v1.A2AServicePromiseClient.prototype.getTask =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.open.agent.v1.A2AService/GetTask',
      request,
      metadata || {},
      methodDescriptor_A2AService_GetTask);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.open.agent.v1.ListTasksRequest,
 *   !proto.alis.open.agent.v1.ListTasksResponse>}
 */
const methodDescriptor_A2AService_ListTasks = new grpc.web.MethodDescriptor(
  '/alis.open.agent.v1.A2AService/ListTasks',
  grpc.web.MethodType.UNARY,
  proto.alis.open.agent.v1.ListTasksRequest,
  proto.alis.open.agent.v1.ListTasksResponse,
  /**
   * @param {!proto.alis.open.agent.v1.ListTasksRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.alis.open.agent.v1.ListTasksResponse.deserializeBinary
);


/**
 * @param {!proto.alis.open.agent.v1.ListTasksRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.alis.open.agent.v1.ListTasksResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.alis.open.agent.v1.ListTasksResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.open.agent.v1.A2AServiceClient.prototype.listTasks =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.open.agent.v1.A2AService/ListTasks',
      request,
      metadata || {},
      methodDescriptor_A2AService_ListTasks,
      callback);
};


/**
 * @param {!proto.alis.open.agent.v1.ListTasksRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.alis.open.agent.v1.ListTasksResponse>}
 *     Promise that resolves to the response
 */
proto.alis.open.agent.v1.A2AServicePromiseClient.prototype.listTasks =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.open.agent.v1.A2AService/ListTasks',
      request,
      metadata || {},
      methodDescriptor_A2AService_ListTasks);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.open.agent.v1.CancelTaskRequest,
 *   !proto.alis.open.agent.v1.Task>}
 */
const methodDescriptor_A2AService_CancelTask = new grpc.web.MethodDescriptor(
  '/alis.open.agent.v1.A2AService/CancelTask',
  grpc.web.MethodType.UNARY,
  proto.alis.open.agent.v1.CancelTaskRequest,
  proto.alis.open.agent.v1.Task,
  /**
   * @param {!proto.alis.open.agent.v1.CancelTaskRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.alis.open.agent.v1.Task.deserializeBinary
);


/**
 * @param {!proto.alis.open.agent.v1.CancelTaskRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.alis.open.agent.v1.Task)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.alis.open.agent.v1.Task>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.open.agent.v1.A2AServiceClient.prototype.cancelTask =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.open.agent.v1.A2AService/CancelTask',
      request,
      metadata || {},
      methodDescriptor_A2AService_CancelTask,
      callback);
};


/**
 * @param {!proto.alis.open.agent.v1.CancelTaskRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.alis.open.agent.v1.Task>}
 *     Promise that resolves to the response
 */
proto.alis.open.agent.v1.A2AServicePromiseClient.prototype.cancelTask =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.open.agent.v1.A2AService/CancelTask',
      request,
      metadata || {},
      methodDescriptor_A2AService_CancelTask);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.open.agent.v1.TaskSubscriptionRequest,
 *   !proto.alis.open.agent.v1.StreamResponse>}
 */
const methodDescriptor_A2AService_TaskSubscription = new grpc.web.MethodDescriptor(
  '/alis.open.agent.v1.A2AService/TaskSubscription',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.alis.open.agent.v1.TaskSubscriptionRequest,
  proto.alis.open.agent.v1.StreamResponse,
  /**
   * @param {!proto.alis.open.agent.v1.TaskSubscriptionRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.alis.open.agent.v1.StreamResponse.deserializeBinary
);


/**
 * @param {!proto.alis.open.agent.v1.TaskSubscriptionRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.alis.open.agent.v1.StreamResponse>}
 *     The XHR Node Readable Stream
 */
proto.alis.open.agent.v1.A2AServiceClient.prototype.taskSubscription =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/alis.open.agent.v1.A2AService/TaskSubscription',
      request,
      metadata || {},
      methodDescriptor_A2AService_TaskSubscription);
};


/**
 * @param {!proto.alis.open.agent.v1.TaskSubscriptionRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.alis.open.agent.v1.StreamResponse>}
 *     The XHR Node Readable Stream
 */
proto.alis.open.agent.v1.A2AServicePromiseClient.prototype.taskSubscription =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/alis.open.agent.v1.A2AService/TaskSubscription',
      request,
      metadata || {},
      methodDescriptor_A2AService_TaskSubscription);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.open.agent.v1.CreateTaskPushNotificationConfigRequest,
 *   !proto.alis.open.agent.v1.TaskPushNotificationConfig>}
 */
const methodDescriptor_A2AService_CreateTaskPushNotificationConfig = new grpc.web.MethodDescriptor(
  '/alis.open.agent.v1.A2AService/CreateTaskPushNotificationConfig',
  grpc.web.MethodType.UNARY,
  proto.alis.open.agent.v1.CreateTaskPushNotificationConfigRequest,
  proto.alis.open.agent.v1.TaskPushNotificationConfig,
  /**
   * @param {!proto.alis.open.agent.v1.CreateTaskPushNotificationConfigRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.alis.open.agent.v1.TaskPushNotificationConfig.deserializeBinary
);


/**
 * @param {!proto.alis.open.agent.v1.CreateTaskPushNotificationConfigRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.alis.open.agent.v1.TaskPushNotificationConfig)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.alis.open.agent.v1.TaskPushNotificationConfig>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.open.agent.v1.A2AServiceClient.prototype.createTaskPushNotificationConfig =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.open.agent.v1.A2AService/CreateTaskPushNotificationConfig',
      request,
      metadata || {},
      methodDescriptor_A2AService_CreateTaskPushNotificationConfig,
      callback);
};


/**
 * @param {!proto.alis.open.agent.v1.CreateTaskPushNotificationConfigRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.alis.open.agent.v1.TaskPushNotificationConfig>}
 *     Promise that resolves to the response
 */
proto.alis.open.agent.v1.A2AServicePromiseClient.prototype.createTaskPushNotificationConfig =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.open.agent.v1.A2AService/CreateTaskPushNotificationConfig',
      request,
      metadata || {},
      methodDescriptor_A2AService_CreateTaskPushNotificationConfig);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.open.agent.v1.GetTaskPushNotificationConfigRequest,
 *   !proto.alis.open.agent.v1.TaskPushNotificationConfig>}
 */
const methodDescriptor_A2AService_GetTaskPushNotificationConfig = new grpc.web.MethodDescriptor(
  '/alis.open.agent.v1.A2AService/GetTaskPushNotificationConfig',
  grpc.web.MethodType.UNARY,
  proto.alis.open.agent.v1.GetTaskPushNotificationConfigRequest,
  proto.alis.open.agent.v1.TaskPushNotificationConfig,
  /**
   * @param {!proto.alis.open.agent.v1.GetTaskPushNotificationConfigRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.alis.open.agent.v1.TaskPushNotificationConfig.deserializeBinary
);


/**
 * @param {!proto.alis.open.agent.v1.GetTaskPushNotificationConfigRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.alis.open.agent.v1.TaskPushNotificationConfig)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.alis.open.agent.v1.TaskPushNotificationConfig>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.open.agent.v1.A2AServiceClient.prototype.getTaskPushNotificationConfig =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.open.agent.v1.A2AService/GetTaskPushNotificationConfig',
      request,
      metadata || {},
      methodDescriptor_A2AService_GetTaskPushNotificationConfig,
      callback);
};


/**
 * @param {!proto.alis.open.agent.v1.GetTaskPushNotificationConfigRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.alis.open.agent.v1.TaskPushNotificationConfig>}
 *     Promise that resolves to the response
 */
proto.alis.open.agent.v1.A2AServicePromiseClient.prototype.getTaskPushNotificationConfig =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.open.agent.v1.A2AService/GetTaskPushNotificationConfig',
      request,
      metadata || {},
      methodDescriptor_A2AService_GetTaskPushNotificationConfig);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.open.agent.v1.ListTaskPushNotificationConfigRequest,
 *   !proto.alis.open.agent.v1.ListTaskPushNotificationConfigResponse>}
 */
const methodDescriptor_A2AService_ListTaskPushNotificationConfig = new grpc.web.MethodDescriptor(
  '/alis.open.agent.v1.A2AService/ListTaskPushNotificationConfig',
  grpc.web.MethodType.UNARY,
  proto.alis.open.agent.v1.ListTaskPushNotificationConfigRequest,
  proto.alis.open.agent.v1.ListTaskPushNotificationConfigResponse,
  /**
   * @param {!proto.alis.open.agent.v1.ListTaskPushNotificationConfigRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.alis.open.agent.v1.ListTaskPushNotificationConfigResponse.deserializeBinary
);


/**
 * @param {!proto.alis.open.agent.v1.ListTaskPushNotificationConfigRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.alis.open.agent.v1.ListTaskPushNotificationConfigResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.alis.open.agent.v1.ListTaskPushNotificationConfigResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.open.agent.v1.A2AServiceClient.prototype.listTaskPushNotificationConfig =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.open.agent.v1.A2AService/ListTaskPushNotificationConfig',
      request,
      metadata || {},
      methodDescriptor_A2AService_ListTaskPushNotificationConfig,
      callback);
};


/**
 * @param {!proto.alis.open.agent.v1.ListTaskPushNotificationConfigRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.alis.open.agent.v1.ListTaskPushNotificationConfigResponse>}
 *     Promise that resolves to the response
 */
proto.alis.open.agent.v1.A2AServicePromiseClient.prototype.listTaskPushNotificationConfig =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.open.agent.v1.A2AService/ListTaskPushNotificationConfig',
      request,
      metadata || {},
      methodDescriptor_A2AService_ListTaskPushNotificationConfig);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.open.agent.v1.GetAgentCardRequest,
 *   !proto.alis.open.agent.v1.AgentCard>}
 */
const methodDescriptor_A2AService_GetAgentCard = new grpc.web.MethodDescriptor(
  '/alis.open.agent.v1.A2AService/GetAgentCard',
  grpc.web.MethodType.UNARY,
  proto.alis.open.agent.v1.GetAgentCardRequest,
  proto.alis.open.agent.v1.AgentCard,
  /**
   * @param {!proto.alis.open.agent.v1.GetAgentCardRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.alis.open.agent.v1.AgentCard.deserializeBinary
);


/**
 * @param {!proto.alis.open.agent.v1.GetAgentCardRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.alis.open.agent.v1.AgentCard)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.alis.open.agent.v1.AgentCard>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.open.agent.v1.A2AServiceClient.prototype.getAgentCard =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.open.agent.v1.A2AService/GetAgentCard',
      request,
      metadata || {},
      methodDescriptor_A2AService_GetAgentCard,
      callback);
};


/**
 * @param {!proto.alis.open.agent.v1.GetAgentCardRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.alis.open.agent.v1.AgentCard>}
 *     Promise that resolves to the response
 */
proto.alis.open.agent.v1.A2AServicePromiseClient.prototype.getAgentCard =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.open.agent.v1.A2AService/GetAgentCard',
      request,
      metadata || {},
      methodDescriptor_A2AService_GetAgentCard);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.open.agent.v1.DeleteTaskPushNotificationConfigRequest,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_A2AService_DeleteTaskPushNotificationConfig = new grpc.web.MethodDescriptor(
  '/alis.open.agent.v1.A2AService/DeleteTaskPushNotificationConfig',
  grpc.web.MethodType.UNARY,
  proto.alis.open.agent.v1.DeleteTaskPushNotificationConfigRequest,
  google_protobuf_empty_pb.Empty,
  /**
   * @param {!proto.alis.open.agent.v1.DeleteTaskPushNotificationConfigRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_protobuf_empty_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.alis.open.agent.v1.DeleteTaskPushNotificationConfigRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.open.agent.v1.A2AServiceClient.prototype.deleteTaskPushNotificationConfig =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.open.agent.v1.A2AService/DeleteTaskPushNotificationConfig',
      request,
      metadata || {},
      methodDescriptor_A2AService_DeleteTaskPushNotificationConfig,
      callback);
};


/**
 * @param {!proto.alis.open.agent.v1.DeleteTaskPushNotificationConfigRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.alis.open.agent.v1.A2AServicePromiseClient.prototype.deleteTaskPushNotificationConfig =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.open.agent.v1.A2AService/DeleteTaskPushNotificationConfig',
      request,
      metadata || {},
      methodDescriptor_A2AService_DeleteTaskPushNotificationConfig);
};


module.exports = proto.alis.open.agent.v1;

