/**
 * @fileoverview gRPC-Web generated client stub for alis.open.support.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v4.24.4
// source: alis/open/support/v1/events.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var alis_open_pubsub_v1_pubsub_pb = require('../../../../alis/open/pubsub/v1/pubsub_pb.js')

var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js')
const proto = {};
proto.alis = {};
proto.alis.open = {};
proto.alis.open.support = {};
proto.alis.open.support.v1 = require('./events_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.alis.open.support.v1.EventsServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.alis.open.support.v1.EventsServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.open.pubsub.v1.PubSubMessage,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_EventsService_HandleEvent = new grpc.web.MethodDescriptor(
  '/alis.open.support.v1.EventsService/HandleEvent',
  grpc.web.MethodType.UNARY,
  alis_open_pubsub_v1_pubsub_pb.PubSubMessage,
  google_protobuf_empty_pb.Empty,
  /**
   * @param {!proto.alis.open.pubsub.v1.PubSubMessage} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_protobuf_empty_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.alis.open.pubsub.v1.PubSubMessage} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.open.support.v1.EventsServiceClient.prototype.handleEvent =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.open.support.v1.EventsService/HandleEvent',
      request,
      metadata || {},
      methodDescriptor_EventsService_HandleEvent,
      callback);
};


/**
 * @param {!proto.alis.open.pubsub.v1.PubSubMessage} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.alis.open.support.v1.EventsServicePromiseClient.prototype.handleEvent =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.open.support.v1.EventsService/HandleEvent',
      request,
      metadata || {},
      methodDescriptor_EventsService_HandleEvent);
};


module.exports = proto.alis.open.support.v1;

