/**
 * @fileoverview gRPC-Web generated client stub for alis.open.validation.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v4.24.4
// source: alis/open/validation/v1/test.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js')

var google_protobuf_field_mask_pb = require('google-protobuf/google/protobuf/field_mask_pb.js')

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js')

var google_type_date_pb = require('../../../../google/type/date_pb.js')
const proto = {};
proto.alis = {};
proto.alis.open = {};
proto.alis.open.validation = {};
proto.alis.open.validation.v1 = require('./test_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.alis.open.validation.v1.BookServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.alis.open.validation.v1.BookServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.open.validation.v1.GetBookRequest,
 *   !proto.alis.open.validation.v1.Book>}
 */
const methodDescriptor_BookService_GetBook = new grpc.web.MethodDescriptor(
  '/alis.open.validation.v1.BookService/GetBook',
  grpc.web.MethodType.UNARY,
  proto.alis.open.validation.v1.GetBookRequest,
  proto.alis.open.validation.v1.Book,
  /**
   * @param {!proto.alis.open.validation.v1.GetBookRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.alis.open.validation.v1.Book.deserializeBinary
);


/**
 * @param {!proto.alis.open.validation.v1.GetBookRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.alis.open.validation.v1.Book)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.alis.open.validation.v1.Book>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.open.validation.v1.BookServiceClient.prototype.getBook =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.open.validation.v1.BookService/GetBook',
      request,
      metadata || {},
      methodDescriptor_BookService_GetBook,
      callback);
};


/**
 * @param {!proto.alis.open.validation.v1.GetBookRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.alis.open.validation.v1.Book>}
 *     Promise that resolves to the response
 */
proto.alis.open.validation.v1.BookServicePromiseClient.prototype.getBook =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.open.validation.v1.BookService/GetBook',
      request,
      metadata || {},
      methodDescriptor_BookService_GetBook);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.open.validation.v1.CreateBookRequest,
 *   !proto.alis.open.validation.v1.Book>}
 */
const methodDescriptor_BookService_CreateBook = new grpc.web.MethodDescriptor(
  '/alis.open.validation.v1.BookService/CreateBook',
  grpc.web.MethodType.UNARY,
  proto.alis.open.validation.v1.CreateBookRequest,
  proto.alis.open.validation.v1.Book,
  /**
   * @param {!proto.alis.open.validation.v1.CreateBookRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.alis.open.validation.v1.Book.deserializeBinary
);


/**
 * @param {!proto.alis.open.validation.v1.CreateBookRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.alis.open.validation.v1.Book)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.alis.open.validation.v1.Book>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.open.validation.v1.BookServiceClient.prototype.createBook =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.open.validation.v1.BookService/CreateBook',
      request,
      metadata || {},
      methodDescriptor_BookService_CreateBook,
      callback);
};


/**
 * @param {!proto.alis.open.validation.v1.CreateBookRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.alis.open.validation.v1.Book>}
 *     Promise that resolves to the response
 */
proto.alis.open.validation.v1.BookServicePromiseClient.prototype.createBook =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.open.validation.v1.BookService/CreateBook',
      request,
      metadata || {},
      methodDescriptor_BookService_CreateBook);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.open.validation.v1.UpdateBookRequest,
 *   !proto.alis.open.validation.v1.Book>}
 */
const methodDescriptor_BookService_UpdateBook = new grpc.web.MethodDescriptor(
  '/alis.open.validation.v1.BookService/UpdateBook',
  grpc.web.MethodType.UNARY,
  proto.alis.open.validation.v1.UpdateBookRequest,
  proto.alis.open.validation.v1.Book,
  /**
   * @param {!proto.alis.open.validation.v1.UpdateBookRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.alis.open.validation.v1.Book.deserializeBinary
);


/**
 * @param {!proto.alis.open.validation.v1.UpdateBookRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.alis.open.validation.v1.Book)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.alis.open.validation.v1.Book>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.open.validation.v1.BookServiceClient.prototype.updateBook =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.open.validation.v1.BookService/UpdateBook',
      request,
      metadata || {},
      methodDescriptor_BookService_UpdateBook,
      callback);
};


/**
 * @param {!proto.alis.open.validation.v1.UpdateBookRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.alis.open.validation.v1.Book>}
 *     Promise that resolves to the response
 */
proto.alis.open.validation.v1.BookServicePromiseClient.prototype.updateBook =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.open.validation.v1.BookService/UpdateBook',
      request,
      metadata || {},
      methodDescriptor_BookService_UpdateBook);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.open.validation.v1.DeleteBookRequest,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_BookService_DeleteBook = new grpc.web.MethodDescriptor(
  '/alis.open.validation.v1.BookService/DeleteBook',
  grpc.web.MethodType.UNARY,
  proto.alis.open.validation.v1.DeleteBookRequest,
  google_protobuf_empty_pb.Empty,
  /**
   * @param {!proto.alis.open.validation.v1.DeleteBookRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_protobuf_empty_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.alis.open.validation.v1.DeleteBookRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.open.validation.v1.BookServiceClient.prototype.deleteBook =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.open.validation.v1.BookService/DeleteBook',
      request,
      metadata || {},
      methodDescriptor_BookService_DeleteBook,
      callback);
};


/**
 * @param {!proto.alis.open.validation.v1.DeleteBookRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.alis.open.validation.v1.BookServicePromiseClient.prototype.deleteBook =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.open.validation.v1.BookService/DeleteBook',
      request,
      metadata || {},
      methodDescriptor_BookService_DeleteBook);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.open.validation.v1.ListBooksRequest,
 *   !proto.alis.open.validation.v1.ListBooksResponse>}
 */
const methodDescriptor_BookService_ListBooks = new grpc.web.MethodDescriptor(
  '/alis.open.validation.v1.BookService/ListBooks',
  grpc.web.MethodType.UNARY,
  proto.alis.open.validation.v1.ListBooksRequest,
  proto.alis.open.validation.v1.ListBooksResponse,
  /**
   * @param {!proto.alis.open.validation.v1.ListBooksRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.alis.open.validation.v1.ListBooksResponse.deserializeBinary
);


/**
 * @param {!proto.alis.open.validation.v1.ListBooksRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.alis.open.validation.v1.ListBooksResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.alis.open.validation.v1.ListBooksResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.open.validation.v1.BookServiceClient.prototype.listBooks =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.open.validation.v1.BookService/ListBooks',
      request,
      metadata || {},
      methodDescriptor_BookService_ListBooks,
      callback);
};


/**
 * @param {!proto.alis.open.validation.v1.ListBooksRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.alis.open.validation.v1.ListBooksResponse>}
 *     Promise that resolves to the response
 */
proto.alis.open.validation.v1.BookServicePromiseClient.prototype.listBooks =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.open.validation.v1.BookService/ListBooks',
      request,
      metadata || {},
      methodDescriptor_BookService_ListBooks);
};


module.exports = proto.alis.open.validation.v1;

